[package]
name = "proxmox-fuse"
version = "5.0.0"
authors = ["Wolfgang Bumiller <w.bumiller@proxmox.com>"]
edition = "2024"
license = "AGPL-3"
description = "Expose fuse requests as async streams."

exclude = [ "build", "debian" ]

[dependencies]
anyhow = "1.0"
bitflags = "2"
futures = "0.3"
libc = "0.2"
tokio = { version = "1.27", features = ["net", "rt"] }

[dev-dependencies]
tokio = { version = "1.27", features = ["macros", "rt-multi-thread", "signal"] }
